/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string }
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'customerPhone' : string,
  'deliveryPincode' : string,
  'createdAt' : Timestamp,
  'deliveryCity' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'priceAtPurchase' : number,
}
export interface OrderItemInput { 'productId' : bigint, 'quantity' : bigint }
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'price' : number,
  'images' : Array<string>,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, string, number, string, Array<string>, bigint],
    bigint
  >,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'createOrder' : ActorMethod<
    [Array<OrderItemInput>, string, string, string, string, string, string],
    bigint
  >,
  'deleteProduct' : ActorMethod<[string, bigint], boolean>,
  'editProduct' : ActorMethod<
    [string, bigint, string, string, number, string, Array<string>, bigint],
    boolean
  >,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listOrders' : ActorMethod<[string], Array<Order>>,
  'listProducts' : ActorMethod<
    [[] | [string], [] | [number], [] | [number]],
    Array<Product>
  >,
  'updateOrderStatus' : ActorMethod<[string, bigint, string], boolean>,
  'verifyAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];